package testng;
import org.testng.annotations.Test;
import java.net.MalformedURLException;
import io.appium.java_client.MobileBy;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.android.AndroidElement;
import io.appium.java_client.android.nativekey.AndroidKey;
import io.appium.java_client.android.nativekey.KeyEvent;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import com.digy4.java.mobiletesting.Digy4AndroidAppTestNGSupport;

public class eBayTestNG {
	@Test
	  public void ebayAndroidTestCase() throws MalformedURLException, InterruptedException {
	    AndroidDriver<AndroidElement> driver = Digy4AndroidAppTestNGSupport.getWebDriver();
	    AndroidElement cross = (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.ImageView[@content-desc='Close']")));
	    cross.click();
	    AndroidElement selling= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//androidx.recyclerview.widget.RecyclerView/android.widget.Button[1]")));
	    selling.click();
	    Thread.sleep(4000);
        driver.pressKey(new KeyEvent().withKey(AndroidKey.BACK));
	    AndroidElement deal= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.Button[@text='Deals']")));
	    deal.click();
	    Thread.sleep(4000);
	    AndroidElement fashion= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.TextView[@text='Fashion']")));
	    fashion.click();
	    Thread.sleep(4000);
	    driver.pressKey(new KeyEvent().withKey(AndroidKey.BACK));
	    Thread.sleep(4000);
	    AndroidElement search= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.id("com.ebay.mobile:id/search_box")));
	    search.click();
	    Thread.sleep(4000);
	    AndroidElement search_text= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.id("com.ebay.mobile:id/search_src_text")));
	    search_text.sendKeys("Cars");
	    Thread.sleep(4000);
	    AndroidElement searcheleclicked= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.RelativeLayout[1]/android.widget.TextView")));
	    searcheleclicked.click();
	    Thread.sleep(4000);
	    AndroidElement modal= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.id("com.ebay.mobile:id/text_slot_1")));
	    modal.click();
	    Thread.sleep(4000);
	    AndroidElement sort= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.id("com.ebay.mobile:id/button_sort")));
	    sort.click();
	    Thread.sleep(4000);
	    AndroidElement sort_option= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.RadioButton[@content-desc='Price + Shipping: lowest first']")));
	    sort_option.click();
	    Thread.sleep(4000);
	    AndroidElement sort1= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.id("com.ebay.mobile:id/button_sort")));
	    sort1.click();
	    Thread.sleep(4000);
	    AndroidElement sort_option1= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.RadioButton[@content-desc='Price + Shipping: highest first']")));
	    sort_option1.click();
	    Thread.sleep(4000);
	    AndroidElement sort2= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.id("com.ebay.mobile:id/button_sort")));
	    sort2.click();
	    Thread.sleep(4000);
	    AndroidElement sort_option2= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.RadioButton[@content-desc='Time: newly listed']")));
	    sort_option2.click();
	    Thread.sleep(4000);
	    AndroidElement sort3= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.id("com.ebay.mobile:id/button_sort")));
	    sort3.click();
	    Thread.sleep(4000);
	    AndroidElement sort_option3= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.RadioButton[@content-desc='Time: ending soonest']")));
	    sort_option3.click();
	    Thread.sleep(4000);
	    AndroidElement sort4= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.id("com.ebay.mobile:id/button_sort")));
	    sort4.click();
	    Thread.sleep(4000);
	    AndroidElement sort_option4= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.RadioButton[@content-desc='Distance: nearest first']")));
	    sort_option4.click();
	    Thread.sleep(4000);
	    AndroidElement Filter= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.id("com.ebay.mobile:id/button_filter")));
	    Filter.click();
	    Thread.sleep(4000);
	    AndroidElement Filter_condition= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.TextView[@text='Condition']")));
	    Filter_condition.click();
	    Thread.sleep(4000);
	    AndroidElement Filter_condition_value= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.TextView[@text='New']")));
	    Filter_condition_value.click();
	    Thread.sleep(4000);
	    AndroidElement Filter_condition_button= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.id("com.ebay.mobile:id/call_to_action_button")));
	    Filter_condition_button.click();
	    Thread.sleep(4000);
	    driver.pressKey(new KeyEvent().withKey(AndroidKey.BACK));
	    AndroidElement deal1= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.Button[@text='Deals']")));
	    deal1.click();
	    Thread.sleep(4000);
	    AndroidElement featured_deals= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.TextView[@content-desc='Featured Deals,7 items']")));
	    featured_deals.click();
	    Thread.sleep(4000);
	    driver.pressKey(new KeyEvent().withKey(AndroidKey.BACK));
	    driver.pressKey(new KeyEvent().withKey(AndroidKey.BACK));
   	    AndroidElement hamburgermenu= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.ImageButton[@content-desc='Main navigation, open']")));
   	    hamburgermenu.click();
	    Thread.sleep(4000);
	    AndroidElement hamburger_selling= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.id("com.ebay.mobile:id/nav_selling")));
	    hamburger_selling.click();
	    Thread.sleep(4000);
	    driver.pressKey(new KeyEvent().withKey(AndroidKey.BACK));
	    AndroidElement hamburgermenu1= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.ImageButton[@content-desc=\"Main navigation, open\"]")));
	    hamburgermenu1.click();
	    Thread.sleep(4000);
	    AndroidElement hamburger_categories= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.id("com.ebay.mobile:id/nav_categories")));
	    hamburger_categories.click();
	    Thread.sleep(4000);
	    AndroidElement categories_baby= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//androidx.recyclerview.widget.RecyclerView/android.widget.FrameLayout[4]/android.widget.ImageView")));
	    categories_baby.click();
	    Thread.sleep(4000);
	    AndroidElement categories_baby_back_arrow= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.ImageButton[@content-desc=\"Navigate up\"]")));
	    categories_baby_back_arrow.click();
	    Thread.sleep(4000);
	    driver.pressKey(new KeyEvent().withKey(AndroidKey.BACK));
	    AndroidElement hamburgermenu2= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("//android.widget.ImageButton[@content-desc=\"Main navigation, open\"]")));
	    hamburgermenu2.click();
	    Thread.sleep(4000);
	    AndroidElement hamburger_deals= (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.id("com.ebay.mobile:id/nav_deals")));
	    hamburger_deals.click();
	    driver.pressKey(new KeyEvent().withKey(AndroidKey.BACK));
	    Thread.sleep(4000);
	    driver.pressKey(new KeyEvent().withKey(AndroidKey.BACK));
	    driver.pressKey(new KeyEvent().withKey(AndroidKey.BACK));
	    
	    //AndroidElement  = (AndroidElement)new WebDriverWait(driver,50).until(ExpectedConditions.elementToBeClickable(MobileBy.xpath("")));
	    //.click();
	    //Thread.sleep(4000);*/
}
}
